@startuml

'--------------------------------------------------
' Meta data of diagram
'--------------------------------------------------
' Title of diagram
title CDSTATS

' Header (top right)
header CDSTATS

' Caption below diagram
caption Database model of CDSTATS

' Footer centered
footer %filename()

' Use orthogonal layouting
skinparam linetype ortho

'--------------------------------------------------
' Entity definitions
'--------------------------------------------------
' Unique MP3 file
entity mp3import {
    unsigned bigint **id_mp3import**
    --
    varchar(512) filename
    datetime(6) date_import
    datetime(6) date_file_mod
    ---
    varchar(256) artist
    varchar(256) album
    varchar(256) title
    varchar(256) genre
    double durationms
    int(11) tracknumber
    int(11) tracktotal
    int(11) year
    int(11) discnumber
    int(11) disctotal
    int(11) bitrate
    double samplerate
}

'--------------------------------------------------
' Legend with explanation
'--------------------------------------------------
legend
**ERM Relation hints:**
Zero or one \t --o|
Exactly one \t --||
Zero or many \t --o{
One or many \t --|{
end legend

@enduml
